name: CI
on: [push]
jobs:
	Test:
		runs-on: ubuntu-latest
		strategy:
			matrix:
				node-version: [<%= nodeEngineVersion %>.x]
		steps:
		- uses: actions/checkout@v2
		- name: Use Node.js ${{ matrix.node-version }}
			uses: actions/setup-node@v1
			with:
				node-version: ${{ matrix.node-version }}<% if ( automatedTests && browserModule && !cloudBrowsers ) { %>
		- run: export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3;<% } %>
		- run: npm install
		- run: npm run lint<% if ( typescript ) { %> && npm run lint:types<% } %>
		- run: npm test<% if ( codeCoverageService ) { %>
	Posttest:
		needs: Test
		steps:
  		- run: npm run posttest:ci<% } %>
